check:
	/home/WAGODOM/u016759/GIT/GITHUB/gcc-linaro.toolchain-2019.12/LINARO.Toolchain-2019.12/arm-linux-gnueabihf/abe/testsuite/test.sh
	/home/WAGODOM/u016759/GIT/GITHUB/gcc-linaro.toolchain-2019.12/LINARO.Toolchain-2019.12/arm-linux-gnueabihf/abe/test.sh

clean:
	rm -fr builds/* sysroots/*

